name: 💬 Support Request
description: Request support for a specific problem you have not been able to solve yourself
title: "[💬 Support Request]: "
labels: ["💬  question"]
body:
  - type: checkboxes
    id: useddocs
    attributes:
      label: Attempted Debugging
      description: |
        I have read the debugging page and seeked resolution or more detail for the issue.
      options:
        - label: I have read the debugging page
          required: true
  - type: checkboxes
    id: searchissue
    attributes:
      label: Searched GitHub Issues
      description: |
        I have searched for the issue and potential resolutions within the [project's GitHub issue list](https://github.com/gmuloc/git-training/issue)
      options:
        - label: I have searched GitHub for the issue.
          required: true
  - type: textarea
    id: scenario
    attributes:
      label: Describe the Scenario
      description: Detail the problem that you're having or what you need support with.
    validations:
      required: true
  - type: input
    id: bsversion
    attributes:
      label: Version
      description: Please provide an exact version.
      placeholder: (eg. v0.0.1)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log Content
      description: If the issue has produced an error, provide any log content below.
      placeholder: Be sure to remove any confidential details in your logs
    validations:
      required: false